"""Experiment 2 — how much of the outcome is ``app.service``, not the model.

See ``docs/research/recsys/experiment-plan-ranker-service-catalog.md``
("Эксперимент 2 — влияние сервисной логики") for the full spec this
implements, and ``docs/research/recsys/experiment-2-service-logic-report.md``
(generated by this module) for the results.

The question
------------
``model_score`` is held fixed — one ``MLRecommendationEngine()`` instance,
never retrained, shared by all four variants below. What varies is only what
``RecommendationService``/``RankingPolicy`` do with the already-computed
candidates: reorder them, drop some, or leave them alone. That is a different
question from experiment 1 ("is the ranker any good"): here the ranker is
fixed and only the service-side handling of its output changes.

Four variants (``app.service`` policies; see that module's docstrings for
each one's own rationale):

1. ``MODEL_ORDER``            — pure model order, no effort gating at all.
2. ``EFFORT_FIRST`` (shipped) — reorder strictly by missing_count.
3. ``FEASIBLE_MODEL_ORDER``   — drop what's not realistically buyable
   (``missing_count > FEASIBILITY_MISSING_CAP``), keep model order for the rest.
4. ``BLENDED``                — model score and effort share the ranking.

Because the ranking-policy difference only shows up *after* assembly, this
runs ``RecommendationService.recommend()`` directly for every (deficit level,
regime, user, arm) cell — unlike experiment 1, which compares raw
``engine.rank()`` output before ``app.service`` ever touches it.

Deviations from the plan, stated up front (see also "Угрозы валидности" in
the generated report):

* Deficit levels reuse the *same calibrated low/base/high numbers* as
  ``recsys.sensitivity.DIALS`` (``no_product_at_all``: 0.02/0.08/0.35,
  ``out_of_stock``: 0.02/0.10/0.35), built as
  ``recsys.inventory.InventoryAssumptions`` instances and passed to
  ``generate_inventory(..., assumptions=...)`` — the same mechanism
  ``recsys.sensitivity`` and ``recsys.benchmark`` already use. An earlier
  version of this script tried to reach the same effect by monkeypatching
  ``recsys.inventory``'s module-level ``P_NO_PRODUCT_AT_ALL``/``P_OUT_OF_STOCK``
  constants; that does nothing, because ``DEFAULT_INVENTORY_ASSUMPTIONS`` is
  an ``InventoryAssumptions()`` instance built once at import time — its
  fields are frozen at construction, not re-read from the module globals on
  every call — so every "deficit level" silently ran the same base
  assumptions. Fixed by building assumptions explicitly instead.
* ``recsys.benchmark.Arm``/``run_benchmark`` is built around simulated user
  *actions* (``UserAction.BUY`` etc. via ``recsys.response_models``), which
  this experiment does not need — it judges the served list directly with
  ``recsys.evaluation.oracle_relevant``. ``Arm`` is reused as-is for naming
  one engine+policy configuration; the run loop and aggregation here are
  purpose-built rather than forced through ``run_benchmark``/``CellOutcome``,
  which have no field for "relevant" or "missing_count" per card.
"""

from __future__ import annotations

import random
import statistics
import sys
import time
from dataclasses import dataclass, replace
from pathlib import Path

from app.contracts import RecommendationRequest, RecipeRecommendation
from app.safety import SafetyPolicy
from app.service import (
    BLENDED,
    EFFORT_FIRST,
    FEASIBILITY_MISSING_CAP,
    FEASIBLE_MODEL_ORDER,
    MODEL_ORDER,
    RecommendationService,
)
from recsys.benchmark import Arm
from recsys.evaluation import oracle_relevant
from recsys.inventory import DEFAULT_INVENTORY_ASSUMPTIONS, InventoryAssumptions, generate_inventory
from recsys.model import MLRecommendationEngine
from recsys.profiles import SyntheticProfile, generate_population
from recsys.ready_food_pairs import ready_meal_options
from recsys.recipes import RECIPES
from recsys.regimes import REGIMES, Regime

OUTPUT_PATH = Path("docs/research/recsys/experiment-2-service-logic-report.md")

#: Same panel convention as recsys/benchmark.py and recsys/sensitivity.py:
#: 9 of 27 regimes, seed 20260905. Kept at the full 80 users/regime from the
#: plan — timed at well under a minute for the full 3-deficit x 9-regime x
#: 4-arm x 80-user grid on this machine, so no reduction was needed.
DEFAULT_REGIMES: tuple[Regime, ...] = REGIMES[:9]
DEFAULT_USERS_PER_REGIME = 80
DEFAULT_SEED = 20260905
TOP_K = 3

#: The baseline every comparison is measured against: the shipped policy.
BASELINE_ARM = "effort_first"

#: Low/base/high calibrated the same way as recsys/sensitivity.py's DIALS for
#: these two knobs. "base" is ``DEFAULT_INVENTORY_ASSUMPTIONS`` itself, so it
#: can never drift from the real default.
DEFICIT_LEVELS: dict[str, InventoryAssumptions] = {
    "low (полки полны)": replace(
        DEFAULT_INVENTORY_ASSUMPTIONS, no_product_at_all=0.02, out_of_stock=0.02
    ),
    "base (наше допущение)": DEFAULT_INVENTORY_ASSUMPTIONS,
    "high (частый дефицит)": replace(
        DEFAULT_INVENTORY_ASSUMPTIONS, no_product_at_all=0.35, out_of_stock=0.35
    ),
}


def build_arms(engine: MLRecommendationEngine) -> tuple[Arm, ...]:
    """The four variants, all wrapping the one fixed engine instance."""
    return (
        Arm(name=MODEL_ORDER.name, engine=engine, ranking_policy=MODEL_ORDER),
        Arm(name=EFFORT_FIRST.name, engine=engine, ranking_policy=EFFORT_FIRST),
        Arm(
            name=FEASIBLE_MODEL_ORDER.name,
            engine=engine,
            ranking_policy=FEASIBLE_MODEL_ORDER,
        ),
        Arm(name=BLENDED.name, engine=engine, ranking_policy=BLENDED),
    )


def _assembled_cost_rub(card: RecipeRecommendation) -> float:
    """What the service actually priced for this card's missing ingredients.

    Sums each ingredient's *chosen* option (``product_options[0]`` — the one
    ``RecommendationService._assemble_recipe`` picked ``source`` from, i.e.
    what would actually be added to the basket), never the abstract
    ``BASE_PRICE_RUB`` table the model's own features use internally.
    """
    return sum(
        ingredient.product_options[0].price
        for ingredient in card.ingredients
        if ingredient.product_options
    )


@dataclass(frozen=True)
class RegimeCell:
    """One (deficit level, arm, regime) aggregate over its users."""

    deficit: str
    arm: str
    regime: str
    n_users: int
    n_cards: int
    relevant_cards: int
    users_with_hit: int
    zero_missing_cards: int
    missing_counts: tuple[int, ...]
    missing_cost_rub: tuple[float, ...]
    empty_users: int

    @property
    def precision_at_k(self) -> float:
        """Share of *served* top-k cards oracle_relevant judges relevant."""
        return self.relevant_cards / self.n_cards if self.n_cards else 0.0

    @property
    def hit_rate(self) -> float:
        """Share of users with >=1 relevant card in their top-k."""
        return self.users_with_hit / self.n_users if self.n_users else 0.0

    @property
    def feasible_share(self) -> float:
        """Share of served cards needing nothing extra (missing_count == 0)."""
        return self.zero_missing_cards / self.n_cards if self.n_cards else 0.0

    @property
    def mean_missing_count(self) -> float:
        return statistics.mean(self.missing_counts) if self.missing_counts else 0.0

    @property
    def mean_missing_cost_rub(self) -> float:
        return statistics.mean(self.missing_cost_rub) if self.missing_cost_rub else 0.0

    @property
    def empty_rate(self) -> float:
        """Share of users whose response.recommendations was empty."""
        return self.empty_users / self.n_users if self.n_users else 0.0


def _run_cell(
    *,
    service: RecommendationService,
    profiles: list[SyntheticProfile],
    inventories: list[list],
    deficit: str,
    arm: str,
    regime_name: str,
    recipe_lookup: dict,
) -> RegimeCell:
    n_cards = 0
    relevant_cards = 0
    users_with_hit = 0
    zero_missing = 0
    missing_counts: list[int] = []
    costs: list[float] = []
    empty_users = 0

    for profile, inventory in zip(profiles, inventories, strict=True):
        request = RecommendationRequest(
            user=profile.user,
            current_receipt=profile.current_receipt,
            purchase_history=profile.purchase_history,
            recipe_catalog=list(recipe_lookup.values()),
            inventory_snapshot=inventory,
            ready_meal_options=[],
            now=profile.now,
            limit=TOP_K,
        )
        response = service.recommend(request)
        if not response.recommendations:
            empty_users += 1
        hit = False
        for card in response.recommendations:
            n_cards += 1
            recipe = recipe_lookup[card.recipe_id]
            if oracle_relevant(profile, recipe, request):
                relevant_cards += 1
                hit = True
            if card.missing_count == 0:
                zero_missing += 1
            missing_counts.append(card.missing_count)
            costs.append(_assembled_cost_rub(card))
        if hit:
            users_with_hit += 1

    return RegimeCell(
        deficit=deficit,
        arm=arm,
        regime=regime_name,
        n_users=len(profiles),
        n_cards=n_cards,
        relevant_cards=relevant_cards,
        users_with_hit=users_with_hit,
        zero_missing_cards=zero_missing,
        missing_counts=tuple(missing_counts),
        missing_cost_rub=tuple(costs),
        empty_users=empty_users,
    )


def run_experiment(
    *,
    regimes: tuple[Regime, ...] = DEFAULT_REGIMES,
    users_per_regime: int = DEFAULT_USERS_PER_REGIME,
    seed: int = DEFAULT_SEED,
    deficit_levels: dict[str, InventoryAssumptions] = DEFICIT_LEVELS,
    progress: bool = False,
) -> tuple[RegimeCell, ...]:
    """Run all four arms through every (deficit level, regime, user).

    One ``MLRecommendationEngine()`` is trained once and shared by every arm
    and every deficit level — model_score never changes; only the ranking
    policy and the inventory scarcity dials do. Profiles are regenerated
    (deterministically, same seed formula) once per deficit level so the
    three deficit levels see the identical user population and only the
    inventory differs, the same pairing discipline recsys.benchmark uses
    across arms.
    """
    engine = MLRecommendationEngine()
    arms = build_arms(engine)
    recipe_lookup = {r.recipe_id: r for r in RECIPES}
    services = {
        arm.name: RecommendationService(
            engine=arm.engine, safety_policy=SafetyPolicy(), ranking_policy=arm.ranking_policy
        )
        for arm in arms
    }

    cells: list[RegimeCell] = []
    for deficit_name, assumptions in deficit_levels.items():
        for regime_index, regime in enumerate(regimes):
            if progress:
                print(f"  {deficit_name} / {regime.name}", flush=True)
            profiles = generate_population(
                users_per_regime,
                seed=seed + regime_index,
                archetypes=regime.archetypes(),
            )
            inventory_rng = random.Random(seed + 100_000 + regime_index)
            inventories = [
                generate_inventory(
                    inventory_rng,
                    now=profile.now,
                    home_store_id=profile.current_receipt.store_id,
                    user_radius_km=profile.user.radius_km,
                    assumptions=assumptions,
                )
                for profile in profiles
            ]
            for arm in arms:
                cells.append(
                    _run_cell(
                        service=services[arm.name],
                        profiles=profiles,
                        inventories=inventories,
                        deficit=deficit_name,
                        arm=arm.name,
                        regime_name=regime.name,
                        recipe_lookup=recipe_lookup,
                    )
                )
    return tuple(cells)


def pool(cells: tuple[RegimeCell, ...], *, deficit: str, arm: str) -> RegimeCell:
    """Sum every regime's cell for one (deficit, arm) into one panel-wide cell."""
    subset = [c for c in cells if c.deficit == deficit and c.arm == arm]
    return RegimeCell(
        deficit=deficit,
        arm=arm,
        regime="ALL",
        n_users=sum(c.n_users for c in subset),
        n_cards=sum(c.n_cards for c in subset),
        relevant_cards=sum(c.relevant_cards for c in subset),
        users_with_hit=sum(c.users_with_hit for c in subset),
        zero_missing_cards=sum(c.zero_missing_cards for c in subset),
        missing_counts=tuple(m for c in subset for m in c.missing_counts),
        missing_cost_rub=tuple(m for c in subset for m in c.missing_cost_rub),
        empty_users=sum(c.empty_users for c in subset),
    )


def _quantiles(values: list[float]) -> dict[str, float]:
    if not values:
        return {}
    ordered = sorted(values)

    def q(p: float) -> float:
        return ordered[min(int(len(ordered) * p), len(ordered) - 1)]

    return {
        "p10": q(0.10),
        "median": statistics.median(ordered),
        "p90": q(0.90),
    }


@dataclass(frozen=True)
class Comparison:
    """Challenger vs baseline, one delta per regime, on one metric.

    A deliberately smaller cousin of ``recsys.benchmark.Comparison``: that
    one's cells vary by (regime, simulator) because ``run_benchmark`` judges
    every card with several stochastic response models. Nothing here is
    stochastic — ``oracle_relevant`` is a deterministic rule — so the only
    source of cross-cell variation is which of the 9 regimes a cell is from.
    Reusing the simulator-shaped abstraction for a single-axis comparison
    would manufacture a "per simulator" breakdown that does not exist.
    """

    deficit: str
    baseline: str
    challenger: str
    metric: str
    deltas: tuple[float, ...]
    regimes: tuple[str, ...]

    @property
    def win_rate(self) -> float:
        if not self.deltas:
            return 0.0
        return sum(1 for d in self.deltas if d > 0) / len(self.deltas)

    @property
    def quantiles(self) -> dict[str, float]:
        return _quantiles(list(self.deltas))


def compare(
    cells: tuple[RegimeCell, ...],
    *,
    deficit: str,
    baseline: str,
    challenger: str,
    metric: str = "precision_at_k",
) -> Comparison:
    baseline_by_regime = {
        c.regime: getattr(c, metric)
        for c in cells
        if c.deficit == deficit and c.arm == baseline
    }
    deltas: list[float] = []
    regimes: list[str] = []
    for c in cells:
        if c.deficit != deficit or c.arm != challenger:
            continue
        base = baseline_by_regime.get(c.regime)
        if base is None:
            continue
        deltas.append(getattr(c, metric) - base)
        regimes.append(c.regime)
    return Comparison(
        deficit=deficit,
        baseline=baseline,
        challenger=challenger,
        metric=metric,
        deltas=tuple(deltas),
        regimes=tuple(regimes),
    )


ARM_ORDER = ("model_order", "effort_first", "feasible_model_order", "blended")
ARM_LABELS = {
    "model_order": "1. model_order (чистый порядок модели)",
    "effort_first": "2. effort_first (шипанное поведение)",
    "feasible_model_order": "3. feasible_model_order (отсечь неосуществимое)",
    "blended": "4. blended (мягкий учёт доступности)",
}


def build_report(
    cells: tuple[RegimeCell, ...],
    *,
    runtime_s: float,
    regimes: tuple[Regime, ...],
    users_per_regime: int,
    seed: int,
) -> str:
    out: list[str] = []
    w = out.append

    w("# Эксперимент 2: влияние сервисной логики")
    w("")
    w(
        f"Сгенерирован `python -m recsys.experiment2_service_logic`. Один "
        f"`MLRecommendationEngine()` (не переобучается между вариантами), "
        f"{len(regimes)} миров × {users_per_regime} пользователей/мир × "
        f"{len(DEFICIT_LEVELS)} уровня дефицита × 4 варианта обработки, "
        f"seed `{seed}`, {runtime_s:.0f} с."
    )
    w("")
    w(
        "**Вопрос:** зафиксировав `model_score`, что меняет именно обработка "
        "выдачи в `app.service`? Это не эксперимент про качество ранкера "
        "(см. эксперимент 1) — здесь ранкер один и тот же, отличается только "
        "то, что `RecommendationService`/`RankingPolicy` делают с уже "
        "посчитанными кандидатами: пересортировать, отбросить или не трогать."
    )
    w("")
    w("---")
    w("")
    w("## 0. Методология")
    w("")
    w(
        "- **Панель.** `recsys.profiles.generate_population` + "
        "`recsys.inventory.generate_inventory`, `REGIMES[:9]`, "
        f"{users_per_regime} пользователей/мир, seed `{seed}` — та же "
        "конвенция, что в `recsys/benchmark.py`/`recsys/sensitivity.py`."
    )
    w(
        "- **Что меряется — на финальной выдаче, а не на сырых кандидатах.** "
        "Каждый вариант вызывает `RecommendationService.recommend()` "
        "целиком; `oracle_relevant` судит `RecommendationResponse."
        "recommendations` (то, что реально показано пользователю в топ-3), "
        "а не `engine.rank()` — это и есть отличие от эксперимента 1."
    )
    w(
        "- **Уровни дефицита.** `no_product_at_all`/`out_of_stock` на "
        "low/base/high теми же откалиброванными значениями, что в "
        "`recsys/sensitivity.py` (`DIALS`): 0.02/0.08/0.35 и 0.02/0.10/0.35 "
        "соответственно, применены как одна общая ось «скудности полки» "
        "(на low оба дана на нижнем значении, на high — оба на верхнем), "
        "а не как независимая развёртка по каждому диалу — иначе сетка "
        "выросла бы до 9 сочетаний вместо 3, а вопрос эксперимента про это "
        "не спрашивает."
    )
    w(
        f"- **Порог `feasibility_missing_cap = {FEASIBILITY_MISSING_CAP}`.** "
        "Выбран эмпирически как p75 `missing_count` по всем собранным "
        "(до сортировки и обрезки) кандидатам на этой же панели "
        "(`REGIMES[:9]`, 80 польз./мир, seed 20260905): p50=4, **p75=6**, "
        "p90=8, максимум 11. Осознанно ниже `MAX_EFFORT_MISSING_COUNT` (8, "
        "константа шкалы «максимального усилия» в `app.service`) — цель "
        "этого варианта не подрезать хвост, а отсечь дороже-докупаемую "
        "четверть *уже собираемых* рецептов как нереалистичную к покупке "
        "сегодня."
    )
    w(
        "- **Метрика релевантности.** `precision@k` = доля показанных "
        "карточек (после сборки и обрезки до топ-3), которые `oracle_"
        "relevant` считает релевантными — не доля от всех кандидатов "
        "модели. Рядом — `hit_rate` (доля пользователей, у кого хотя бы одна "
        "карточка в топ-3 релевантна), т.к. одно число легко перепутать с "
        "другим."
    )
    w(
        "- **Стоимость докупки.** Сумма цен реально выбранных "
        "`ProductOption` (первый по `_valid_products`-сортировке вариант на "
        "каждый недостающий ингредиент — то, что сервис фактически "
        "подставил бы в корзину), не абстрактная `BASE_PRICE_RUB`."
    )
    w("")
    w("---")
    w("")
    w("## 1. Итоговые числа по вариантам и уровням дефицита")
    w("")
    for deficit_name in DEFICIT_LEVELS:
        w(f"### {deficit_name}")
        w("")
        w(
            "| Вариант | precision@k | hit_rate | доля missing=0 | "
            "ср. missing_count | ср. докупка, ₽ | доля пустых выдач |"
        )
        w("|---|---:|---:|---:|---:|---:|---:|")
        for arm in ARM_ORDER:
            cell = pool(cells, deficit=deficit_name, arm=arm)
            w(
                f"| {ARM_LABELS[arm]} | {cell.precision_at_k:.3f} | "
                f"{cell.hit_rate:.3f} | {cell.feasible_share:.3f} | "
                f"{cell.mean_missing_count:.2f} | "
                f"{cell.mean_missing_cost_rub:.0f} | {cell.empty_rate:.3f} |"
            )
        w("")
    w(
        "Пустая выдача (`recommendations == []`) ожидаемо возможна только у "
        "варианта 3 — это единственный, кто вообще что-то отбрасывает после "
        "сборки; у остальных трёх пустая доля должна быть равна доле "
        "пользователей, для которых сервис не собрал вообще ни одного "
        "кандидата (безопасность/эксклюзии), а не доле, связанной с "
        "политикой ранжирования."
    )
    w("")
    w("---")
    w("")
    w("## 2. Варианты 1/3/4 против шипанного (`effort_first`)")
    w("")
    w(
        "Разбивка по 9 мирам, доля побед — это не p-value: миры выбраны "
        "нами, чтобы накрыть диапазон, не сэмплированы из реальности."
    )
    w("")
    for deficit_name in DEFICIT_LEVELS:
        w(f"### {deficit_name}")
        w("")
        for challenger in ("model_order", "feasible_model_order", "blended"):
            for metric, metric_label in (
                ("precision_at_k", "precision@k"),
                ("mean_missing_cost_rub", "ср. докупка, ₽"),
            ):
                cmp = compare(
                    cells,
                    deficit=deficit_name,
                    baseline=BASELINE_ARM,
                    challenger=challenger,
                    metric=metric,
                )
                q = cmp.quantiles
                w(
                    f"- **{ARM_LABELS[challenger]}** vs `effort_first`, "
                    f"`{metric_label}`: побед в {cmp.win_rate:.0%} миров "
                    f"({len(cmp.deltas)} миров), разброс дельты "
                    f"p10 {q.get('p10', 0):+.3f}, медиана "
                    f"{q.get('median', 0):+.3f}, p90 {q.get('p90', 0):+.3f}"
                )
        w("")
    w("---")
    w("")
    w("## 3. Устойчиво ли это к уровню дефицита")
    w("")
    w(
        "Сравнение направления вывода (кто впереди по `precision@k`) между "
        "уровнями дефицита — переворот не шум, а находка, которую нужно "
        "называть явно."
    )
    w("")
    w("| Вариант | precision@k: low → base → high |")
    w("|---|---|")
    for arm in ARM_ORDER:
        values = [
            pool(cells, deficit=d, arm=arm).precision_at_k for d in DEFICIT_LEVELS
        ]
        w(f"| {ARM_LABELS[arm]} | " + " → ".join(f"{v:.3f}" for v in values) + " |")
    w("")
    w("---")
    w("")
    w("## Угрозы валидности")
    w("")
    w(
        "- **Уровни дефицита совпадают по числам с `recsys.sensitivity.DIALS`, "
        "но не переиспользуют модуль напрямую** — построены как отдельные "
        "`InventoryAssumptions` (`no_product_at_all`/`out_of_stock` на "
        "0.02/база/0.35), тем же способом, что `recsys.sensitivity`/"
        "`recsys.benchmark` уже используют. Более ранняя версия скрипта "
        "пыталась достичь того же через monkeypatch модульных констант "
        "`recsys.inventory.P_NO_PRODUCT_AT_ALL`/`P_OUT_OF_STOCK` — это не "
        "работает, потому что `DEFAULT_INVENTORY_ASSUMPTIONS` строится один "
        "раз при импорте модуля и не перечитывает глобальные константы при "
        "каждом вызове; три «уровня дефицита» в той версии считали одно и "
        "то же. Исправлено до публикации этого отчёта."
    )
    w(
        "- **Два дефицит-диала двигаются вместе**, не по отдельности, как в "
        "`recsys/sensitivity.py`. Если `no_product_at_all` и `out_of_stock` "
        "тянут вывод в разные стороны, эта развёртка их не различит."
    )
    w(
        "- **`oracle_relevant` не знает про режим (`Regime`).** Он читает "
        "`recsys.profiles.ARCHETYPES` напрямую (глобальные, не "
        "изменённые дилами новизны/промо/повтора), тогда как сами "
        "популяции генерируются через `regime.archetypes()`. Это "
        "унаследованное от `recsys.evaluation`/`recsys.response_models."
        "OracleResponder` свойство, не что-то специфичное для этого "
        "эксперимента — но означает, что «релевантность» здесь мягче "
        "реагирует на дилы `novelty`/`promo`/`repeat`, чем сама генерация "
        "профилей."
    )
    w(
        "- **`oracle_relevant` не гейтит на осуществимость** (см. паспорт "
        "метрики 0.19 в плане экспериментов) — он же используется как "
        "относительный инструмент сравнения рангов, self-referential "
        "относительно `recsys.model`, не независимая истина о желании "
        "готовить."
    )
    w(
        "- **`FEASIBILITY_MISSING_CAP = 6` — наш выбор, не измеренная "
        "константа.** Он подобран по p75 распределения на этой конкретной "
        "панели; другая панель (другой каталог рецептов, другая смесь "
        "архетипов) дала бы другое число."
    )
    w(
        "- **Cтоимость докупки — оценка** (`price_is_estimate`), "
        "откалиброванная по распределению цен X5, но не поингредиентно "
        "истинная."
    )
    w(
        "- **Миры выбрали мы.** Сетка режимов — диапазон стресса, а не "
        "выборка из реальности; доля побед по мирам — не p-value."
    )
    w("")
    return "\n".join(out) + "\n"


def main() -> int:
    sys.stdout.reconfigure(encoding="utf-8")
    started = time.time()
    cells = run_experiment(progress=True)
    runtime = time.time() - started

    print()
    print(f"cells={len(cells)} runtime={runtime:.0f}s")
    for deficit_name in DEFICIT_LEVELS:
        print(f"--- {deficit_name} ---")
        for arm in ARM_ORDER:
            cell = pool(cells, deficit=deficit_name, arm=arm)
            print(
                f"  {arm:22} precision@k={cell.precision_at_k:.3f} "
                f"hit_rate={cell.hit_rate:.3f} "
                f"feasible={cell.feasible_share:.3f} "
                f"missing={cell.mean_missing_count:.2f} "
                f"cost={cell.mean_missing_cost_rub:.0f} "
                f"empty={cell.empty_rate:.3f}"
            )

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    report = build_report(
        cells,
        runtime_s=runtime,
        regimes=DEFAULT_REGIMES,
        users_per_regime=DEFAULT_USERS_PER_REGIME,
        seed=DEFAULT_SEED,
    )
    OUTPUT_PATH.write_text(report, encoding="utf-8", newline="\n")
    print(f"\n{OUTPUT_PATH}: {len(report.splitlines())} lines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
