"""Paired comparison between arms, with the interval clustered where it belongs.

Why this replaced win-rate-over-cells
-------------------------------------
The bench compared arms by counting cells — "B beats A in 78% of (world x
simulator) cells". That framing was forced by the old setup: nine small
populations, one per behavioural world, so a cell was the only unit available.
It has two costs. A cell aggregates away the pairing that actually exists (the
*same shopper* saw both arms), and a share of cells is not an effect size, so
"78% of cells" says nothing about how much better B is.

Once every arm runs on one panel, the natural unit is the shopper. Each user
contributes one delta per comparison, the deltas are paired by construction —
same person, same basket, same shelf, only the arm differs — and the spread
across users is the thing to put an interval on.

Bootstrap resamples **users**, not cards. One shopper's three cards are one
opinion about one basket; treating them as three independent observations
narrows the interval by roughly sqrt(3) for no reason. Same argument as
``recsys.human_eval._bootstrap_ci`` makes about raters.
"""

from __future__ import annotations

import random
import statistics
from dataclasses import dataclass, field


@dataclass(frozen=True)
class PairedResult:
    """One challenger against one baseline, over the users they both served."""

    baseline: str
    challenger: str
    metric: str
    n_users: int
    baseline_mean: float
    challenger_mean: float
    #: Mean of the per-user differences. Equals the difference of means, but is
    #: computed pairwise because that is what the interval is built from.
    mean_delta: float
    ci_low: float
    ci_high: float
    #: Share of users where the challenger did strictly better. Reported
    #: alongside the effect, never instead of it: a change can help 80% of
    #: people by a hair and hurt 20% badly.
    win_share: float
    tie_share: float
    warnings: list[str] = field(default_factory=list)

    @property
    def is_significant(self) -> bool:
        """Does the 95% interval exclude zero?

        Not a p-value and not a licence to say "proven": the population is
        synthetic and the users were generated by us. It answers the narrower
        question of whether this panel can tell the two arms apart at all.
        """
        return self.ci_low > 0.0 or self.ci_high < 0.0

    def summary(self) -> str:
        verdict = "различимо" if self.is_significant else "неразличимо"
        return (
            f"{self.challenger} vs {self.baseline} по {self.metric}: "
            f"{self.baseline_mean:.3f} -> {self.challenger_mean:.3f}, "
            f"дельта {self.mean_delta:+.3f} "
            f"[{self.ci_low:+.3f}, {self.ci_high:+.3f}], "
            f"лучше у {self.win_share:.0%} пользователей, {verdict}"
        )


def paired_compare(
    baseline_by_user: dict[str, float],
    challenger_by_user: dict[str, float],
    *,
    baseline: str,
    challenger: str,
    metric: str,
    iterations: int = 2000,
    seed: int = 20260905,
) -> PairedResult:
    """Compare two arms over the users both of them served.

    Users missing from either side are dropped rather than treated as zero: an
    arm that failed to serve someone did not score zero for them, it produced
    no observation, and imputing one invents data.
    """
    shared = sorted(set(baseline_by_user) & set(challenger_by_user))
    warnings: list[str] = []
    dropped = len(set(baseline_by_user) | set(challenger_by_user)) - len(shared)
    if dropped:
        warnings.append(f"{dropped} users served by only one arm were dropped")

    if not shared:
        return PairedResult(
            baseline=baseline,
            challenger=challenger,
            metric=metric,
            n_users=0,
            baseline_mean=0.0,
            challenger_mean=0.0,
            mean_delta=0.0,
            ci_low=0.0,
            ci_high=0.0,
            win_share=0.0,
            tie_share=0.0,
            warnings=[*warnings, "no shared users: nothing to compare"],
        )

    deltas = [challenger_by_user[u] - baseline_by_user[u] for u in shared]
    wins = sum(1 for d in deltas if d > 0)
    ties = sum(1 for d in deltas if d == 0)

    rng = random.Random(seed)
    means: list[float] = []
    n = len(deltas)
    for _ in range(iterations):
        means.append(statistics.mean(rng.choice(deltas) for _ in range(n)))
    means.sort()
    low = means[int(0.025 * len(means))]
    high = means[min(int(0.975 * len(means)), len(means) - 1)]

    if n < 30:
        warnings.append(f"only {n} shared users: the interval is wide by construction")

    return PairedResult(
        baseline=baseline,
        challenger=challenger,
        metric=metric,
        n_users=n,
        baseline_mean=statistics.mean(baseline_by_user[u] for u in shared),
        challenger_mean=statistics.mean(challenger_by_user[u] for u in shared),
        mean_delta=statistics.mean(deltas),
        ci_low=low,
        ci_high=high,
        win_share=wins / n,
        tie_share=ties / n,
        warnings=warnings,
    )


def bootstrap_mean(
    values_by_user: dict[str, float],
    *,
    iterations: int = 2000,
    seed: int = 20260905,
) -> tuple[float, float, float]:
    """Mean and 95% interval for one arm, resampling users."""
    users = sorted(values_by_user)
    if not users:
        return 0.0, 0.0, 0.0
    point = statistics.mean(values_by_user[u] for u in users)
    if len(users) < 2:
        return point, point, point

    rng = random.Random(seed)
    means: list[float] = []
    for _ in range(iterations):
        means.append(
            statistics.mean(values_by_user[rng.choice(users)] for _ in users)
        )
    means.sort()
    return (
        point,
        means[int(0.025 * len(means))],
        means[min(int(0.975 * len(means)), len(means) - 1)],
    )
